name: foobar
version: 0.1
date: 2018-10-02
description: |
    quux

authors:
    - name: Max Horn
      url: https://www.quendi.de/math

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.9"

www: https://fingolfin.github.io/foobar/
readme: README.md
packageinfo: https://fingolfin.github.io/foobar/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/fingolfin/foobar/releases/download/v0.1/foobar-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Hor18</span>]   <b class='BibAuthor'>Horn, M.</b>,
     <i class='BibTitle'>foobar, quux,
             Version 0.1</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://fingolfin.github.io/foobar/">https://fingolfin.github.io/foobar/</a></span>.
    </p>
    

bibtex: |
    @misc{ foobar0.1,
      author =           {Horn, M.},
      title =            {{foobar}, quux, {V}ersion 0.1},
      month =            {Oct},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href {https://fingolfin.github.io/foobar/} {\texttt{https://fingolfin.github.io/}\discretionary {}{}{}\texttt{foobar/}}},
      printedkey =       {Hor18}
    }

